### ISSUE TITLE
Audit Log for Postgres Proxy

### ISSUE THREAD

**Issue by tiennguyenskedulo** [kviklet/kviklet#267]
Hi, 

I'm experimenting with the Postgres Proxy experimental feature. Everything is working fine but I don't have any logs for the queries. I only see `Started proxy for user on port 5438` log. Audit log is still available for queries ran using the web interface.

Its stated in readme that:
`Postgres Proxy: Start a proxy server to use the DB Client of your choice, but everything will be stored in the Kviklet Auditlog.`
And 
`Any executed statements are logged in the auditlog as if they were run via the web interface.`

So I expect to see logs indicating that a query is executed by this specific user and potentially via this request.

Could you please confirm if this is an expected behaviour or is there any flag or setting I need to enable to have logs for Postgres Proxy Queries?

Thank you for your assistance.

**Comment by Askir** [comment]
Hey, thanks for the bug report. The proxy is a bit of an experimental feature. More a POC than something I'd recommend to use in production. I have no tests for it either so this could have broken by another feature release.

That being said the audit log should work. I'll look into it in the coming says thanks!

**Comment by Askir** [comment]
Hey, sorry I got to this very late. Got caught up in another topic. I tried this out and cannot reproduce your behaviour I run the server and ran some queries via datagrip and they show up in the auditlog just fine. Could you share which client you are using and maybe also which postgres version?

**Comment by tiennguyenskedulo** [comment]
I'm using psql to make the queries. I'm using postgres version 16 for kviklet database, and potgres version 14.9 for the database I need to proxy into. This is the manifest file content that I use to set everything up.
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kviklet
  namespace: kviklet
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      {{ kube_pod_selector_labels | to_nice_yaml(indent=2) | indent(6) }}
  template:
    metadata:
      labels:
        {{ kube_deployment_labels | to_nice_yaml(indent=2) | indent(8) }}
    spec:
      containers:
        - name: postgres
          imagePullPolicy: IfNotPresent
          image: postgres:16
          resources:
            {{ kube_deployment_resources | to_nice_yaml(indent=2) | indent(12) }}
          ports:
            - name: http
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: kviklet
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
        - name: kviklet
          imagePullPolicy: IfNotPresent
          image: ghcr.io/kviklet/kviklet:main
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            {{ kube_deployment_resources | to_nice_yaml(indent=2) | indent(12) }}
          ports:
            - name: http
              containerPort: 8080
            - name: proxy
              containerPort: 5438
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://localhost:5432/kviklet
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: INITIAL_USER_EMAIL
              value: admin@admin.com
            - name: INITIAL_USER_PASSWORD
              value: admin
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: postgres-storage
          emptyDir: {}
```
