### ISSUE TITLE
LDAP not binding with principal

### ISSUE THREAD

**Issue by niklju** [kviklet/kviklet#277]
Hi, I'm trying to set up kviklet to authorize with our Freeipa environment using LDAPS. I seem to have gotten everything working with CA certificate installation, correct dn for users etc, but it seems that the admin password is not actually used for binding. Because the users email can't be found. I suspect this since Freeipa seems to enable anonymous binding by default, but this only gives certain fields:

```
# This is a direct command from our environment, but the sensitive parts masked
ldapsearch -x -H ldap://ipa.example.com -b "cn=users,cn=accounts,dc=example,dc=com" "(uid=username)"
# extended LDIF
#
# LDAPv3
# base <cn=users,cn=accounts,dc=example,dc=com> with scope subtree
# filter: (uid=username)
# requesting: ALL
#

# username, users, accounts, example.com
dn: uid=username,cn=users,cn=accounts,dc=example,dc=com
ipaNTSecurityIdentifier: XXXX
cn: Firstname Surname
displayName: Firstname Surname
gecos: Firstname Surname
gidNumber: 111111111
givenName: Firstname
homeDirectory: /home/username
initials: FS
loginShell: /bin/bash
objectClass: top
objectClass: person
objectClass: organizationalperson
objectClass: inetorgperson
objectClass: inetuser
objectClass: posixaccount
objectClass: krbprincipalaux
objectClass: krbticketpolicyaux
objectClass: ipaobject
objectClass: ipasshuser
objectClass: ipaSshGroupOfPubKeys
objectClass: mepOriginEntry
objectClass: ipantuserattrs
sn: surname
uid: username
uidNumber: 111111111

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

When I authorise with a user and password, I get a lot more fields, including **mail**

```
ldapsearch -x -H ldap://ipa.example.com -b "cn=users,cn=accounts,dc=example,dc=com" -D uid=ADMINUSER,cn=sysaccounts,cn=etc,dc=example,dc=com -w SUPERLONGPASSWORD "(uid=username)"
```

The errors I get are attached [kvikletlog.log](https://github.com/user-attachments/files/18573307/kvikletlog.log)

But the most vital parts are here:
```
2 2025-01-28T11:27:07.846Z DEBUG 7 --- [nio-8081-exec-6] o.s.security.web.FilterChainProxy        : Securing POST /login
  3 2025-01-28T11:27:07.852Z DEBUG 7 --- [nio-8081-exec-6] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
  4 2025-01-28T11:27:07.853Z DEBUG 7 --- [nio-8081-exec-6] o.s.security.web.FilterChainProxy        : Secured POST /login
  5 2025-01-28T11:27:07.862Z DEBUG 7 --- [nio-8081-exec-6] org.hibernate.SQL                        : select u1_0.id,u1_0.email,u1_0.full_name,u1_0.ldap_identifier,u1_0.password,u1_0.subject from "user" u1_0          where u1_0.email=?
  6 2025-01-28T11:27:07.864Z DEBUG 7 --- [nio-8081-exec-6] o.s.s.l.a.BindAuthenticator              : Failed to bind with any user DNs []
  7 2025-01-28T11:27:07.940Z DEBUG 7 --- [nio-8081-exec-6] o.s.s.ldap.SpringSecurityLdapTemplate    : Found DN: uid=nilj,cn=users,cn=accounts
  8 2025-01-28T11:27:07.942Z DEBUG 7 --- [nio-8081-exec-6] o.s.s.l.s.FilterBasedLdapUserSearch      : Found user 'nilj', with FilterBasedLdapUserSearch [searchFilter=(uid={0}); searchBase=cn=users,cn=accounts;        scope=subtree; searchTimeLimit=0; derefLinkFlag=false ]
  9 2025-01-28T11:27:08.006Z DEBUG 7 --- [nio-8081-exec-6] o.s.s.l.a.BindAuthenticator              : Bound uid=nilj,cn=users,cn=accounts,dc=example,dc=com
 10 2025-01-28T11:27:08.092Z ERROR 7 --- [nio-8081-exec-6] d.k.k.c.ExceptionHandlerController       : Exception occurred at /login
```

I assume this is relevant `Failed to bind with any user DNs []` , but I can't find why this would fail, I've repeatedly copy pasted the environment variables used in the docker compose and it works 100% of the time.

My docker compose looks like this:

```
services:
  kviklet-postgres:
    container_name: kviklet-postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: kviklet
      POSTGRES_PASSWORD: SECRET
      POSTGRES_DB: kviklet_db
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
    network_mode: host
    volumes:
      - ./kviklet-postgres-data:/var/lib/postgresql/data

  kviklet:
    container_name: kviklet
    image: ghcr.io/kviklet/kviklet:main
    network_mode: host
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://127.0.0.1:5432/kviklet_db
      - SPRING_DATASOURCE_USERNAME=SECRET
      - SPRING_DATASOURCE_PASSWORD=SECRET
      - INITIAL_USER_EMAIL=user@example.com
      - INITIAL_USER_PASSWORD=SECRET
      - LDAP_ENABLED=true
      - LDAP_URL=ldaps://ipa.example.com:636
      - LDAP_BASE=dc=example,dc=com
      - LDAP_PRINCIPAL=uid=ADMINUSER,cn=sysaccounts,cn=etc,dc=example,dc=com
      - LDAP_PASSWORD=ADMINPASSWORD
      - LDAP_UNIQUE_IDENTIFIER_ATTRIBUTE=uid
      - LDAP_EMAIL_ATTRIBUTE=mail
      - LDAP_FULL_NAME_ATTRIBUTE=cn
      - LDAP_USER_OU=people
      - LDAP_SEARCH_BASE=cn=users,cn=accounts
      - ENCRYPTION_ENABLED=true
      - ENCRYPTION_KEY_CURRENT=SECRET
    depends_on:
      - kviklet-postgres
    restart: unless-stopped
```

I've tried going through the code, but I'm a sysadmin not a kotlin developer so I am a bit at a loss. Is it possible to verify that LDAP_PASSWORD is actually used? Any advice is much appreciated!
